### ISSUE TITLE
Setup instruction is missing

### ISSUE THREAD

**Issue by beigirad** [AbolfaZlRezaEe/WeatherNotFound#12]
I got the open-weather key from its website. 

But there's no instruction to use it in sample project.

> you should check `weatherNotFound.properties` file and make sure you specified the needed parameter...

But it has ignored and doesn't exist as a template for use.

**Comment by AbolfaZlRezaEe** [comment]
Thank you for mentioning that! 

Yes, I should've written a README.md file for using sample project. I will write the README and then close this issue.

**Comment by AbolfaZlRezaEe** [comment]
Requirements for running Sample project were written. now you can check it out [here](https://github.com/AbolfaZlRezaEe/WeatherNotFound/pull/14)!
